export interface BusinessName {
  id: string;
  name: string;
  origin: string;
  meaning: string;
  category: string;
  personality: string;
  linguisticRoot: "Sanskrit" | "Hindi" | "Marathi" | "Urdu" | "Hybrid";
  description: string;
  suitableFor: string[];
  tags: string[];
}

export const businessNames: BusinessName[] = [
  // Expertise & Skill Category
  {
    id: "1",
    name: "NipunTech",
    origin: "Hindi/Sanskrit",
    meaning: "Nipun: Skilled, Expert, Proficient",
    category: "Expertise & Skill",
    personality: "Professional, High-Skill, Reliable",
    linguisticRoot: "Sanskrit",
    description: "Emphasizes the quality and expertise of the technician. Perfect for a premium, high-skill marketplace.",
    suitableFor: ["Technical Services", "Appliance Repair", "Smart Home Setup"],
    tags: ["expertise", "professional", "skill", "technician"],
  },
  {
    id: "2",
    name: "KushalFix",
    origin: "Hindi/Sanskrit",
    meaning: "Kushal: Expert, Clever, Competent",
    category: "Expertise & Skill",
    personality: "Competent, Trustworthy, Efficient",
    linguisticRoot: "Sanskrit",
    description: "A slightly softer, more approachable feel than Nipun. Conveys competence and trustworthiness.",
    suitableFor: ["Home Repairs", "Electrical Work", "Plumbing"],
    tags: ["competent", "trustworthy", "efficient", "repair"],
  },
  {
    id: "3",
    name: "GyanSeva",
    origin: "Hindi/Sanskrit",
    meaning: "Gyan: Knowledge, Wisdom. Seva: Service",
    category: "Expertise & Skill",
    personality: "Knowledge-Driven, Intelligent Service",
    linguisticRoot: "Sanskrit",
    description: "Appeals to clients seeking diagnostic expertise and knowledge-based solutions.",
    suitableFor: ["Technical Diagnostics", "IT Support", "Consulting"],
    tags: ["knowledge", "wisdom", "service", "intelligent"],
  },
  {
    id: "4",
    name: "VishwasTech",
    origin: "Hindi",
    meaning: "Vishwas: Trust, Faith",
    category: "Expertise & Skill",
    personality: "Trustworthy, Secure, Dependable",
    linguisticRoot: "Hindi",
    description: "Directly addresses the key market challenge of trust. Strong for building client confidence.",
    suitableFor: ["All Technical Services", "Home Services", "Appliance Repair"],
    tags: ["trust", "faith", "secure", "dependable"],
  },
  {
    id: "5",
    name: "KaushalPro",
    origin: "Hindi/Sanskrit",
    meaning: "Kaushal: Skill, Expertise",
    category: "Expertise & Skill",
    personality: "Premium, Expert-Level Service",
    linguisticRoot: "Sanskrit",
    description: "Suitable for the high-end technical niche market. Premium positioning.",
    suitableFor: ["Premium Services", "Advanced Repairs", "Specialized Tech"],
    tags: ["skill", "expertise", "premium", "professional"],
  },

  // Service & Help Category
  {
    id: "6",
    name: "KarigarConnect",
    origin: "Hindi/Urdu",
    meaning: "Karigar: Artisan, Craftsman, Skilled Worker",
    category: "Service & Help",
    personality: "Community-Focused, Authentic, Connecting",
    linguisticRoot: "Hindi",
    description: "Connects clients directly with the artisan. Highly recognizable and authentic.",
    suitableFor: ["Handyman Services", "Craftwork", "Local Services"],
    tags: ["artisan", "craftsman", "community", "authentic"],
  },
  {
    id: "7",
    name: "MistryFix",
    origin: "Hindi/Marathi",
    meaning: "Mistry: Mechanic, Technician",
    category: "Service & Help",
    personality: "Direct, Simple, Local",
    linguisticRoot: "Marathi",
    description: "Highly recognizable term for a skilled repair person. Direct and simple.",
    suitableFor: ["General Repairs", "Maintenance", "Quick Fixes"],
    tags: ["mechanic", "technician", "local", "direct"],
  },
  {
    id: "8",
    name: "SahayTech",
    origin: "Hindi",
    meaning: "Sahay: Help, Assistance",
    category: "Service & Help",
    personality: "Supportive, Reliable Help",
    linguisticRoot: "Hindi",
    description: "Simple name that clearly communicates the core function of assistance.",
    suitableFor: ["Support Services", "Assistance", "Help Desk"],
    tags: ["help", "assistance", "support", "reliable"],
  },
  {
    id: "9",
    name: "SevaFix",
    origin: "Hindi/Sanskrit",
    meaning: "Seva: Service, Duty",
    category: "Service & Help",
    personality: "Service-Oriented, Dedicated",
    linguisticRoot: "Sanskrit",
    description: "A classic, well-understood term for service. Strong cultural resonance.",
    suitableFor: ["All Services", "General Services", "Maintenance"],
    tags: ["service", "duty", "dedicated", "oriented"],
  },
  {
    id: "10",
    name: "AasaanRepair",
    origin: "Hindi",
    meaning: "Aasaan: Easy, Simple",
    category: "Service & Help",
    personality: "Convenient, Hassle-Free",
    linguisticRoot: "Hindi",
    description: "Focuses on the ease of the client experience. Perfect for convenience-focused platforms.",
    suitableFor: ["Quick Services", "Easy Repairs", "Convenience Services"],
    tags: ["easy", "simple", "convenient", "hassle-free"],
  },

  // Modern & Efficient Category
  {
    id: "11",
    name: "QuickSeva",
    origin: "English + Hindi",
    meaning: "Quick: Fast. Seva: Service",
    category: "Modern & Efficient",
    personality: "Fast, On-Demand, Efficient",
    linguisticRoot: "Hybrid",
    description: "Appeals to the urban consumer's need for speed and efficiency.",
    suitableFor: ["On-Demand Services", "Quick Fixes", "Urgent Services"],
    tags: ["quick", "fast", "efficient", "on-demand"],
  },
  {
    id: "12",
    name: "TechDost",
    origin: "English + Hindi",
    meaning: "Tech: Technology. Dost: Friend",
    category: "Modern & Efficient",
    personality: "Friendly, Approachable, Technical",
    linguisticRoot: "Hybrid",
    description: "Positions the service as a trusted partner and friend. Approachable yet technical.",
    suitableFor: ["Tech Support", "IT Services", "Smart Home"],
    tags: ["tech", "friend", "approachable", "support"],
  },
  {
    id: "13",
    name: "SmartKarigar",
    origin: "English + Hindi",
    meaning: "Smart: Intelligent. Karigar: Artisan",
    category: "Modern & Efficient",
    personality: "Modern, Intelligent, Skilled",
    linguisticRoot: "Hybrid",
    description: "Highlights the use of technology and high-skill work. Modern and professional.",
    suitableFor: ["Smart Home Services", "Tech Integration", "Advanced Repairs"],
    tags: ["smart", "intelligent", "modern", "skilled"],
  },
  {
    id: "14",
    name: "FixNow India",
    origin: "English + Geographic",
    meaning: "Fix Now: Immediate Action. India: Geographic Anchor",
    category: "Modern & Efficient",
    personality: "Action-Oriented, Immediate",
    linguisticRoot: "Hybrid",
    description: "Clear, action-oriented name with a geographical anchor. Suitable for urgent services.",
    suitableFor: ["Urgent Services", "Emergency Repairs", "Quick Response"],
    tags: ["immediate", "action", "urgent", "india"],
  },
  {
    id: "15",
    name: "ProTech India",
    origin: "English + Geographic",
    meaning: "Pro: Professional. Tech: Technology",
    category: "Modern & Efficient",
    personality: "Professional, Global-sounding, Local",
    linguisticRoot: "Hybrid",
    description: "Clear, professional name anchored to the local market. Global yet local.",
    suitableFor: ["Professional Services", "Tech Services", "Premium Services"],
    tags: ["professional", "technology", "india", "global"],
  },
];

export const categories = [
  "Expertise & Skill",
  "Service & Help",
  "Modern & Efficient",
];

export const linguisticRoots = [
  "Sanskrit",
  "Hindi",
  "Marathi",
  "Urdu",
  "Hybrid",
];
