/**
 * API Configuration for Servesetu Application
 * Centralized API endpoints and configuration
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';
const API_TIMEOUT = parseInt(import.meta.env.VITE_API_TIMEOUT || '30000');
const WEBSOCKET_URL = import.meta.env.VITE_WEBSOCKET_URL || 'ws://localhost:8000/ws';

export const apiConfig = {
  baseURL: API_BASE_URL,
  timeout: API_TIMEOUT,
  headers: {
    'Content-Type': 'application/json',
  },
};

export const wsConfig = {
  url: WEBSOCKET_URL,
  reconnection: true,
  reconnectionDelay: 1000,
  reconnectionDelayMax: 5000,
  reconnectionAttempts: 5,
};

export const apiEndpoints = {
  // Authentication
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    verifyOtp: '/auth/verify-otp',
    socialLogin: '/auth/social-login',
    refreshToken: '/auth/refresh-token',
    logout: '/auth/logout',
    resetPassword: '/auth/reset-password',
  },

  // Customer endpoints
  customer: {
    profile: '/customers/:customerId',
    updateProfile: '/customers/:customerId',
    addresses: '/customers/:customerId/addresses',
    bookings: '/customers/:customerId/bookings',
    bookingDetail: '/customers/:customerId/bookings/:bookingId',
    reviews: '/customers/:customerId/reviews',
    wallet: '/customers/:customerId/wallet',
    disputes: '/customers/:customerId/disputes',
  },

  // Technician endpoints
  technician: {
    profile: '/technicians/:technicianId',
    updateProfile: '/technicians/:technicianId',
    onboarding: '/technicians/onboarding',
    documents: '/technicians/:technicianId/documents',
    availability: '/technicians/:technicianId/availability',
    bookings: '/technicians/:technicianId/bookings',
    earnings: '/technicians/:technicianId/earnings',
    payouts: '/technicians/:technicianId/payouts',
    performance: '/technicians/:technicianId/performance',
    portfolio: '/technicians/:technicianId/portfolio',
  },

  // Services
  services: {
    list: '/services',
    categories: '/services/categories',
    detail: '/services/:serviceId',
  },

  // Bookings
  booking: {
    create: '/bookings',
    list: '/bookings',
    detail: '/bookings/:bookingId',
    update: '/bookings/:bookingId',
    cancel: '/bookings/:bookingId/cancel',
    accept: '/bookings/:bookingId/accept',
    reject: '/bookings/:bookingId/reject',
    complete: '/bookings/:bookingId/complete',
  },

  // Payments
  payment: {
    createOrder: '/payments/order',
    verifyPayment: '/payments/verify',
    getPaymentDetail: '/payments/:paymentId',
    listPayments: '/payments',
    wallet: '/payments/wallet',
    addToWallet: '/payments/wallet/add',
    getWalletTransactions: '/payments/wallet/transactions',
    requestRefund: '/payments/:paymentId/refund',
    getRefundDetail: '/payments/refunds/:refundId',
    listRefunds: '/payments/refunds',
    requestPayout: '/payments/payouts',
    getPayoutDetail: '/payments/payouts/:payoutId',
    listPayouts: '/payments/payouts',
    cancelPayout: '/payments/payouts/:payoutId/cancel',
    addPaymentMethod: '/payments/methods',
    removePaymentMethod: '/payments/methods/:methodId',
    getPaymentMethods: '/payments/methods',
    history: '/payments/history',
  },

  payments: {
    createOrder: '/payments/order',
    verifyPayment: '/payments/verify',
    getPaymentDetail: '/payments/:paymentId',
    listPayments: '/payments',
    wallet: '/payments/wallet',
    addToWallet: '/payments/wallet/add',
    getWalletTransactions: '/payments/wallet/transactions',
    requestRefund: '/payments/:paymentId/refund',
    getRefundDetail: '/payments/refunds/:refundId',
    listRefunds: '/payments/refunds',
    requestPayout: '/payments/payouts',
    getPayoutDetail: '/payments/payouts/:payoutId',
    listPayouts: '/payments/payouts',
    cancelPayout: '/payments/payouts/:payoutId/cancel',
    addPaymentMethod: '/payments/methods',
    removePaymentMethod: '/payments/methods/:methodId',
    getPaymentMethods: '/payments/methods',
    history: '/payments/history',
  },

  // Messages/Chat
  message: {
    list: '/messages/:bookingId',
    send: '/messages',
    getMessages: '/messages/:sessionId',
    getMessageDetail: '/messages/:id',
    editMessage: '/messages/:id',
    deleteMessage: '/messages/:id',
    markAsRead: '/messages/:messageId/read',
    markSessionAsRead: '/messages/sessions/:sessionId/read',
    searchMessages: '/messages/:sessionId/search',
    createSession: '/messages/sessions',
    getSessionDetail: '/messages/sessions/:id',
    listSessions: '/messages/sessions',
    updateSession: '/messages/sessions/:id',
    archiveSession: '/messages/sessions/:id/archive',
    deleteSession: '/messages/sessions/:id',
    typingIndicator: '/messages/sessions/:sessionId/typing',
    updateStatus: '/messages/status',
    getStatus: '/messages/status',
    uploadAttachment: '/messages/attachments',
    deleteAttachment: '/messages/attachments/:id',
    downloadAttachment: '/messages/attachments/:id/download',
    getUnreadCount: '/messages/unread-count',
    clearUnread: '/messages/sessions/:sessionId/clear-unread',
  },

  messages: {
    list: '/messages/:bookingId',
    send: '/messages',
    getMessages: '/messages/:sessionId',
    getMessageDetail: '/messages/:id',
    editMessage: '/messages/:id',
    deleteMessage: '/messages/:id',
    markAsRead: '/messages/:messageId/read',
    markSessionAsRead: '/messages/sessions/:sessionId/read',
    searchMessages: '/messages/:sessionId/search',
    createSession: '/messages/sessions',
    getSessionDetail: '/messages/sessions/:id',
    listSessions: '/messages/sessions',
    updateSession: '/messages/sessions/:id',
    archiveSession: '/messages/sessions/:id/archive',
    deleteSession: '/messages/sessions/:id',
    typingIndicator: '/messages/sessions/:sessionId/typing',
    updateStatus: '/messages/status',
    getStatus: '/messages/status',
    uploadAttachment: '/messages/attachments',
    deleteAttachment: '/messages/attachments/:id',
    downloadAttachment: '/messages/attachments/:id/download',
    getUnreadCount: '/messages/unread-count',
    clearUnread: '/messages/sessions/:sessionId/clear-unread',
  },

  // Reviews & Ratings
  reviews: {
    createReview: '/reviews',
    getReviewDetail: '/reviews/:id',
    listReviews: '/reviews',
    updateReview: '/reviews/:reviewId',
    deleteReview: '/reviews/:reviewId',
    addResponse: '/reviews/:id/responses',
    updateResponse: '/reviews/responses/:id',
    deleteResponse: '/reviews/responses/:id',
    getRatingDistribution: '/reviews/:technicianId/rating-distribution',
    getAverageRating: '/reviews/:technicianId/average-rating',
    getMyReviews: '/reviews/me',
    getReceivedReviews: '/reviews/received',
    approveReview: '/reviews/:id/approve',
    rejectReview: '/reviews/:id/reject',
    flagReview: '/reviews/:id/flag',
    getFlaggedReviews: '/reviews/flagged',
    markHelpful: '/reviews/:id/mark-helpful',
    markUnhelpful: '/reviews/:id/mark-unhelpful',
    removeHelpfulVote: '/reviews/:id/helpful-vote',
    uploadImage: '/reviews/:id/image',
    deleteImage: '/reviews/:id/image',
  },

  // Disputes
  dispute: {
    create: '/disputes',
    list: '/disputes',
    detail: '/disputes/:disputeId',
    update: '/disputes/:disputeId',
    resolve: '/disputes/:disputeId/resolve',
    submitEvidence: '/disputes/:disputeId/evidence',
    getEvidence: '/disputes/:disputeId/evidence',
    deleteEvidence: '/disputes/:disputeId/evidence/:evidenceId',
    submitResolution: '/disputes/:disputeId/resolution',
    getResolution: '/disputes/:disputeId/resolution',
    acceptResolution: '/disputes/:disputeId/resolution/accept',
    rejectResolution: '/disputes/:disputeId/resolution/reject',
    finalizeResolution: '/disputes/:disputeId/resolution/finalize',
    sendMessage: '/disputes/:disputeId/messages',
    getMessages: '/disputes/:disputeId/messages',
    getStatistics: '/disputes/statistics',
    getEscalations: '/disputes/escalations',
    assignArbiter: '/disputes/:disputeId/arbiter',
    escalateDispute: '/disputes/:disputeId/escalate',
    requestMediation: '/disputes/:disputeId/mediation',
    acceptMediation: '/disputes/:disputeId/mediation/accept',
    declineMediation: '/disputes/:disputeId/mediation/decline',
  },

  disputes: {
    create: '/disputes',
    list: '/disputes',
    detail: '/disputes/:disputeId',
    update: '/disputes/:disputeId',
    resolve: '/disputes/:disputeId/resolve',
    submitEvidence: '/disputes/:disputeId/evidence',
    getEvidence: '/disputes/:disputeId/evidence',
    deleteEvidence: '/disputes/:disputeId/evidence/:evidenceId',
    submitResolution: '/disputes/:disputeId/resolution',
    getResolution: '/disputes/:disputeId/resolution',
    acceptResolution: '/disputes/:disputeId/resolution/accept',
    rejectResolution: '/disputes/:disputeId/resolution/reject',
    finalizeResolution: '/disputes/:disputeId/resolution/finalize',
    sendMessage: '/disputes/:disputeId/messages',
    getMessages: '/disputes/:disputeId/messages',
    getStatistics: '/disputes/statistics',
    getEscalations: '/disputes/escalations',
    assignArbiter: '/disputes/:disputeId/arbiter',
    escalateDispute: '/disputes/:disputeId/escalate',
    requestMediation: '/disputes/:disputeId/mediation',
    acceptMediation: '/disputes/:disputeId/mediation/accept',
    declineMediation: '/disputes/:disputeId/mediation/decline',
  },

  // Admin endpoints
  admin: {
    dashboard: '/admin/dashboard',
    getDashboard: '/admin/dashboard',
    users: '/admin/users',
    listUsers: '/admin/users',
    getUserDetail: '/admin/users/:id',
    suspendUser: '/admin/users/:id/suspend',
    unsuspendUser: '/admin/users/:id/unsuspend',
    deactivateUser: '/admin/users/:id/deactivate',
    reactivateUser: '/admin/users/:id/reactivate',
    blockUser: '/admin/users/:id/block',
    unblockUser: '/admin/users/:id/unblock',
    updateUserRole: '/admin/users/:id/role',
    technicians: '/admin/technicians',
    listTechnicians: '/admin/technicians',
    verifyTechnicianDocuments: '/admin/technicians/:id/verify-documents',
    getTechnicianVerificationStatus: '/admin/technicians/:id/verification-status',
    penalizeTechnician: '/admin/technicians/:id/penalize',
    bookings: '/admin/bookings',
    listBookings: '/admin/bookings',
    cancelBooking: '/admin/bookings/:id/cancel',
    disputes: '/admin/disputes',
    getContentReports: '/admin/reports/content',
    approveContent: '/admin/reports/content/:id/approve',
    removeContent: '/admin/reports/content/:id',
    getFlaggedReviews: '/admin/reviews/flagged',
    analytics: '/admin/analytics',
    getAnalytics: '/admin/analytics',
    getSystemHealth: '/admin/system/health',
    settings: '/admin/settings',
    getSettings: '/admin/settings',
    updateSettings: '/admin/settings',
    getServiceCategories: '/admin/service-categories',
    addServiceCategory: '/admin/service-categories',
    updateServiceCategory: '/admin/service-categories/:id',
    generateReport: '/admin/reports/generate',
    getReportStatus: '/admin/reports/:id/status',
    exportData: '/admin/reports/export',
    sendBulkNotification: '/admin/notifications/bulk',
    getNotificationTemplates: '/admin/notifications/templates',
    updateNotificationTemplate: '/admin/notifications/templates/:id',
  },

  // Support
  support: {
    tickets: '/support/tickets',
    createTicket: '/support/tickets',
    ticketDetail: '/support/tickets/:ticketId',
    replyTicket: '/support/tickets/:ticketId/reply',
    listTickets: '/support/tickets',
    updateTicket: '/support/tickets/:ticketId',
    closeTicket: '/support/tickets/:ticketId/close',
    reopenTicket: '/support/tickets/:ticketId/reopen',
    addTicketMessage: '/support/tickets/:ticketId/messages',
    getTicketMessages: '/support/tickets/:ticketId/messages',
    uploadTicketAttachment: '/support/tickets/:ticketId/attachments',
    searchFAQ: '/support/faqs/search',
    getFAQByCategory: '/support/faqs/categories/:category',
    markFAQHelpful: '/support/faqs/:id/helpful',
    getHelpArticles: '/support/articles',
    getArticleDetail: '/support/articles/:id',
    startLiveChat: '/support/live-chat',
    sendChatMessage: '/support/live-chat/:sessionId/messages',
    getChatHistory: '/support/live-chat/:sessionId/messages',
    endLiveChat: '/support/live-chat/:sessionId/end',
    getAgentAvailability: '/support/live-chat/availability',
    submitTicketFeedback: '/support/tickets/:ticketId/feedback',
    getSurvey: '/support/surveys',
    submitSurveyResponse: '/support/surveys/:surveyId/response',
    getContactInfo: '/support/contact',
    getSupportStatistics: '/support/statistics',
  },

  // Notifications
  notification: {
    list: '/notifications',
    getNotifications: '/notifications',
    markAsRead: '/notifications/:notificationId/read',
    markAllAsRead: '/notifications/read-all',
    deleteNotification: '/notifications/:notificationId',
    deleteAllNotifications: '/notifications',
    getUnreadCount: '/notifications/unread-count',
    getSettings: '/notifications/settings',
    updateSettings: '/notifications/settings',
    getFrequencyPreferences: '/notifications/frequency',
    updateFrequencyPreferences: '/notifications/frequency',
    getEmailHistory: '/notifications/email/history',
    resendEmail: '/notifications/email/:id/resend',
    getSMSHistory: '/notifications/sms/history',
    resendSMS: '/notifications/sms/:id/resend',
    registerDevice: '/notifications/devices',
    unregisterDevice: '/notifications/devices/:id',
    getRegisteredDevices: '/notifications/devices',
    getDigest: '/notifications/digest',
    getTemplates: '/notifications/templates',
    previewNotification: '/notifications/preview',
    getStatistics: '/notifications/statistics',
    sendTestNotification: '/notifications/test',
  },
  notifications: {
    list: '/notifications',
    getNotifications: '/notifications',
    markAsRead: '/notifications/:notificationId/read',
    markAllAsRead: '/notifications/read-all',
    deleteNotification: '/notifications/:notificationId',
    deleteAllNotifications: '/notifications',
    getUnreadCount: '/notifications/unread-count',
    getSettings: '/notifications/settings',
    updateSettings: '/notifications/settings',
    getFrequencyPreferences: '/notifications/frequency',
    updateFrequencyPreferences: '/notifications/frequency',
    getEmailHistory: '/notifications/email/history',
    resendEmail: '/notifications/email/:id/resend',
    getSMSHistory: '/notifications/sms/history',
    resendSMS: '/notifications/sms/:id/resend',
    registerDevice: '/notifications/devices',
    unregisterDevice: '/notifications/devices/:id',
    getRegisteredDevices: '/notifications/devices',
    getDigest: '/notifications/digest',
    getTemplates: '/notifications/templates',
    previewNotification: '/notifications/preview',
    getStatistics: '/notifications/statistics',
    sendTestNotification: '/notifications/test',
  },
};

export default {
  apiConfig,
  wsConfig,
  apiEndpoints,
};
